CREATE DATABASE gestorIA;
USE gestorIA;

CREATE TABLE IF NOT EXISTS expenses (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    AMOUNT DECIMAL NOT NULL,
    DATE DATE NOT NULL,
    CATEGORY VARCHAR(50),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS expensesPLN (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    CATEGORIA VARCHAR(100) NOT NULL,
    AMOUNT DECIMAL NOT NULL,
    DATE DATE NOT NULL,
    PROMPT VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS expensesOCR (
	ID INT AUTO_INCREMENT PRIMARY KEY,
    CATEGORIA VARCHAR(100) NOT NULL,
    AMOUNT DECIMAL NOT NULL,
    DATE DATE NOT NULL,
    NOMBRE VARCHAR(255) NOT NULL,
	CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- DROP TABLE expensesPLN;
-- DROP TABLE expensesOCR;
SELECT * FROM expenses;
SELECT * FROM expensesPLN;
SELECT * FROM expensesOCR;